pipeline {
	agent any 
	
	environment {
		// Choose destination folder to place built appImage in:
		ARTIFACT_FOLDER = '/tmp'
	}

	stages {
		stage('Clean workspace') {
			steps {
    	        deleteDir();
			}
		}
		stage('Checking gcc availability') {
			steps {
				script {
					if(fileExists('/usr/bin/gcc')) {
						echo 'gcc found'
					} else {
						echo 'Error: Cant find gcc.'
						Environment.Exit(1)
					}
				}
			}
		}
		stage('Checking curses availability') {
				steps {
				script {
					if(fileExists('/usr/include/curses.h')) {
						echo 'curses found.'
					} else {
						echo 'Error: Cant find curses.'
						Environment.Exit(1)
					}
				}
			}
		}
		stage('Checkout repo') {
			steps {
				echo 'Cloning beings repo'
				git url: 'https://github.com/schnitz81/beings.git'
			}
		}
        stage('Compile') {
			steps {
				echo 'Compiling...'
				sh 'gcc -v -Wall -c ai.c'
				sh 'gcc -v -Wall -c being.c'
				sh 'gcc -v -Wall -c event.c'
				sh 'gcc -v -Wall -c main.c'
				sh 'gcc -v -Wall -c world.c'
				sh 'gcc -v -o beings main.o ai.o event.o being.o world.o -lcurses'
			}
		}
		stage('Test of executable existance') {
			steps {
				echo 'Checking if file exists'
				fileExists('beings')
			}
		}
		stage('Stash executable and repo files') {
			steps {
				stash includes: 'beings', name: 'executable'
//				stash includes: 'icon.png', name: 'icon'
//				stash includes: 'beings.desktop', name: 'desktop'
//				stash includes: 'AppRun', name: 'apprun'
			}
		}
		stage('Clean workspace before appImage deps preparation') {
			steps {
    	        deleteDir();
			}
		}
		stage('Checkout of appImage deps') {
			steps {
				echo 'Cloning Jenkins repo'
				git url: 'https://github.com/schnitz81/Jenkinsfiles.git'
			}
		}
		stage('Create appImage fs') {
			steps {
				echo "Creating fs for appImage"
				sh 'mkdir -pv beings-appfs/lib64'
				sh 'mkdir -pv beings-appfs/usr/bin'
			}
		}
		stage('Put appimage files in appfs') {
			steps {
				echo "Putting necessary appimage files in appfs..."
				sh 'mv -v beings/AppRun beings-appfs/'
				sh 'mv -v beings/beings.desktop beings-appfs/'
				sh 'mv -v beings/icon.png beings-appfs/'
			}
		}
		
		stage('Unstash executable') {
			steps {
				dir('beings-appfs/usr/bin') {
					echo 'Unstashing and naming executable'
					unstash 'executable'
					sh 'mv beings beings.x64'
				}
			}
		}
		stage('Solve and copy lib dependencies') {
			steps {
				dir('beings-appfs/usr/bin') {
					echo "Copying libs..." 
					sh "noOfLibs=`ldd beings.x64 | grep -ce '\\/lib\\(.*\\)\\ '` && \ 
					echo \$noOfLibs libs to be copied. && \
					for i in `seq 1 \$noOfLibs`; do cp -v `ldd beings.x64 | grep -oe '\\/lib\\(.*\\)\\ ' | head -n \$i | tail -n 1` ../../lib64/ ; done"
				}
			}
		}

    }
}
