pipeline {
	agent any 
	
	environment {
		// Choose destination folder to place built appImage in:
		ARTIFACT_FOLDER = '/tmp'
	}

	stages {
		stage('Clean workspace') {
			steps {
    	        deleteDir();
			}
		}
		stage('Checking gcc availability') {
			steps {
				script {
					if(fileExists('/usr/bin/gcc')) {
						echo 'gcc found'
					} else {
						echo 'Error: Cant find gcc.'
						Environment.Exit(1)
					}
				}
			}
		}
		stage('Checking curses availability') {
				steps {
				script {
					if(fileExists('/usr/include/curses.h')) {
						echo 'curses found.'
					} else {
						echo 'Error: Cant find curses.'
						Environment.Exit(1)
					}
				}
			}
		}
		stage('Checking mikmod availability') {
				steps {
				script {
					if(fileExists('/usr/include/mikmod.h')) {
						echo 'mikmod found.'
					} else {
						echo 'Error: Cant find mikmod. Install mikmod dev package.'
						Environment.Exit(1)
					}
				}
			}
		}
		stage('Checkout repo') {
			steps {
				echo 'Cloning beings repo'
				git url: 'https://github.com/schnitz81/textmode-lifestyle.git'
			}
		}
        stage('Compile') {
			steps {
				echo 'Compiling...'
				sh 'gcc -v -Wall -c main.c'
				sh 'gcc -v -Wall -c loop.c'
				sh 'gcc -v -Wall -c bouncer.c'
				sh 'gcc -v -Wall -c scroller.c'
				sh 'gcc -v -Wall -c dotbar.c'
				sh 'gcc -v -Wall -c banner.c'
				sh 'gcc -v -Wall -c tune.c'
				sh 'gcc -v -o textmode-lifestyle.x64 main.o loop.o bouncer.o scroller.o dotbar.o banner.o tune.o -lcurses -lmikmod -lpthread'
			}
		}
		stage('Stash executable') {
			steps {
				echo 'Stashing executable.'
				stash includes: 'textmode-lifestyle.x64', name: 'executable'
			}
		}
		stage('Clean workspace before appImage deps preparation') {
			steps {
    	        deleteDir();
			}
		}
		stage('Checkout of appImage deps') {
			steps {
				echo 'Cloning Jenkins repo'
				git url: 'https://github.com/schnitz81/Jenkinsfiles.git'
			}
		}
		stage('Create appImage fs') {
			steps {
				echo "Creating fs for appImage"
				sh 'mkdir -pv textmode-lifestyle-appfs/usr/lib'
				sh 'mkdir -pv textnode.lifestyle-appfs/usr/bin'
			}
		}
		stage('Put appimage files in appfs') {
			steps {
				echo "Putting necessary appimage files in appfs..."
				sh 'mv -v textmode-lifestyle/AppRun textmode-lifestyle-appfs/'
				sh 'chmod a+x textmode-lifestyle-appfs/AppRun'
				sh 'mv -v textmode-lifestyle/textmode-lifestyle.desktop textmode-lifestyle-appfs/'
				sh 'mv -v textmode-lifestyle/icon.png textmode-lifestyle-appfs/'
			}
		}
		
		stage('Unstash executable') {
			steps {
				dir('textmode-lifestyle-appfs/usr/bin') {
					echo 'Unstashing and naming executable'
					unstash 'executable'
				}
			}
		}
		stage('Solve and copy lib dependencies') {
			steps {
				dir('textmode-lifestyle-appfs/usr/bin') {
					echo "Copying libs..." 
					sh script: """
					   noOfLibs=`ldd textmode-lifestyle.x64 | grep -ce '\\/lib\\(.*\\)\\ '`
					   echo \$noOfLibs libs to be copied.
					   for i in `seq 1 \$noOfLibs`; do cp -v `ldd textmode-lifestyle.x64 | grep -oe ' \\/lib\\(.*\\)\\ ' | head -n \$i | tail -n 1` ../lib/ ; done 
					   for i in `seq 1 \$noOfLibs`; do cp -v `ldd textmode-lifestyle.x64 | grep -oe ' \\/usr\\/lib\\(.*\\)\\ ' | head -n \$i | tail -n 1` ../lib/ ; done
					""", returnStdout: true
				}
			}
		}
		stage('Download appimagetool') {
			steps {
				sh 'wget http://schnitz.se/test/appimagetool-x86_64.AppImage'
				sh 'chmod -v +x appimagetool-x86_64.AppImage'
			}
		}
		stage('Build appimage') {
			steps {
				sh 'ARCH=x86_64 ./appimagetool-x86_64.AppImage -v ./textmode-lifestyle-appfs textmode-lifestyle-x86_64.AppImage'
			}
		}
		stage('Distribute appimage') {
			steps {
				sh 'mv -v textmode-lifestyle*.AppImage ${ARTIFACT_FOLDER}/'
			}
		}
    }
}
